name: Deploy Secret Page
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Associate this job with the "github-pages" environment
    environment: github-pages  # 🎯 Key addition
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Page with Secret
        env:
          # Pull secret from the environment (not repository secrets)
          SECRET_CONTENT: ${{ secrets.SECRET_MESSAGE }}
        run: |
          echo "::add-mask::$SECRET_CONTENT"
          mkdir -p public
          echo "<h1>Secret: $SECRET_CONTENT</h1>" > public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true