name: Deploy Static Content with Dynamic Updates

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '59 16 * * *'  # 00:59 HKT
    - cron: '59 23 * * *'  # 06:59 HKT
    - cron: '59 1 * * *'   # 09:59 HKT
    - cron: '59 2 * * *'   # 10:59 HKT
    - cron: '59 3 * * *'   # 11:59 HKT
    - cron: '59 4 * * *'   # 12:59 HKT
    - cron: '59 5 * * *'   # 13:59 HKT
    - cron: '59 6 * * *'   # 14:59 HKT
    - cron: '59 7 * * *'   # 15:59 HKT
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Show Job started
        run: echo "Job started at $(date +'%Y-%m-%d %H:%M:%S %Z')"
      - name: Checkout code
        uses: actions/checkout@v4

      # Clone the private repo using the PAT
      - name: Clone private repo
        run: |
          git clone https://${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/trifectastudio/easy-concert-src.git
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      # - name: Create dummy folder
      #   run: mkdir -p public

      # - name: Copy files
      #   run: |
      #     cp -r easy-concert-src/public/* public/

      # - name: change directory to easy-concert-src
      #   run: |
      #     cd easy-concert-src
      - name: Verify copied files (DEBUG)
        run: |
          echo "Current directory structure:"
          pwd
          ls -al
      # Add this new step here
      - name: Update sitemap lastmod date
        working-directory: easy-concert-src
        run: |
          sed -i "s/<lastmod>.*<\/lastmod>/<lastmod>$(date +%F)<\/lastmod>/" public/sitemap.xml

      - name: Verify copied files (DEBUG)
        working-directory: easy-concert-src
        run: |
          echo "Current directory structure:"
          pwd
          ls -al
      # Add Node.js setup if not already present in your environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify your Node.js version
      - name: Install dependencies
        run: npm install html-minifier-terser uglify-js terser
      # Run gen.js after copying files
      - name: Generate dynamic content
        working-directory: easy-concert-src/public
        run: node find-events.js # Ensure gen.js is in the current directory after copying
      - name: Run minification script
        working-directory: easy-concert-src
        run: node minify-all.js
      - name: Verify copied files (DEBUG)
        working-directory: easy-concert-src/public
        run: |
          echo "Current directory structure:"
          pwd
          ls -al
      # - name: Copy non-HTML and non-JS files to dist
      #   working-directory: easy-concert-src
      #   run: |
      #     mkdir -p dist
      #     find public -type f ! -name "*.html" ! -name "*.js" -exec cp --parents {} dist/ \;
      - name: Copy non-JS and non-HTML files from public to dist
        run: |
          find public -type f -not -name "*.js" -not -name "*.html" -exec cp {} dist/ \;
        working-directory: easy-concert-src
      - name: Verify copied files (DEBUG)
        working-directory: easy-concert-src/dist
        run: |
          echo "Current directory structure:"
          pwd
          ls -al

      # - name: change directory to root
      #   run: |
      #     cd ..
      - name: Copy everything from easy-concert-src/dist to root
        run: |
          cp -r easy-concert-src/dist/* .
      - name: Verify copied files (DEBUG)
        run: |
          echo "Current directory structure:"
          pwd
          ls -al
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Corrected path to upload from the current directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4